FROM ubuntu:xenial

MAINTAINER "matthieu.simonin@inria.fr"

RUN apt update && apt install -y git python
RUN git clone git://git.apache.org/qpid-dispatch.git /qpid-dispatch
WORKDIR /qpid-dispatch/console/stand-alone
RUN git checkout -b 1.0.0
EXPOSE 8000
CMD ["python","-m", "SimpleHTTPServer"]

