FROM ubuntu:xenial

MAINTAINER "matthieu.simonin@inria.fr"

RUN apt update && apt install -y git python
RUN git clone https://github.com/apache/qpid-dispatch /qpid-dispatch
WORKDIR /qpid-dispatch/console/stand-alone
RUN git checkout -b 1.0.0

# in 1.0.0 we need to npm install all the deps
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt install -y nodejs
RUN npm install

EXPOSE 8000
CMD ["python","-m", "SimpleHTTPServer"]

