FROM ubuntu:xenial

MAINTAINER "matthieu.simonin@inria.fr"

RUN apt update && apt install -y git python
RUN mkdir -p /opt
WORKDIR /opt
RUN git clone --depth 1 --branch 0.8.0 git://git.apache.org/qpid-dispatch.git
WORKDIR qpid-dispatch/console/stand-alone

EXPOSE 8000

CMD ["python","-m", "SimpleHTTPServer"]

