# qdrouterd and his collectd friend are packaged together
# We use this base image which provide an init script allowing
# several daemon to be started
FROM msimonin/qdrouterd:DISPATCH-957

MAINTAINER "matthieu.simonin@inria.fr"

# Install collectd
RUN apt update
RUN apt install -y collectd git
RUN git clone --depth 1 https://github.com/ajssmith/collectd-qdrouterd /opt/collectd-qdrouterd

WORKDIR /opt/collectd-qdrouterd
RUN cat config/types.db.custom >> /usr/share/collectd/types.db

# runit scripts
ADD runit /etc/service


# Some cleaning
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


WORKDIR /
ENTRYPOINT ["/sbin/my_init"]
