---
- name: Generate the configuration file
  template:
    src: oslo_messaging.conf.j2
    dest: /oslo_messaging.conf

- name: Create ombt-data directory for the agent(s)
  file:
    path: "{{ item.log | dirname }}"
    mode: 0777
    state: directory
  with_items: "{{ ombt_confs[agent_type][inventory_hostname] }}"
  when: inventory_hostname in ombt_confs[agent_type]

- name: Create the agent output log file
  file:
    path: "{{ item.log }}"
    mode: 0777
    state: touch
  with_items: "{{ ombt_confs['controller'][inventory_hostname] }}"
  when: inventory_hostname in ombt_confs[agent_type]

- name: Start ombt controller(s)
  docker_container:
    image: "{{ ombt_version }}"
    command: "{{ item.command }}"
    name: "{{ item.name }}"
    detach: "{{ item.detach }}"
    network_mode: host
    state: started
    volumes:
      - "{{ item.log }}:{{item.docker_log}}"
      - "/oslo_messaging.conf:/oslo_messaging.conf"
  with_items: "{{ ombt_confs['controller'][inventory_hostname] }}"
  when: inventory_hostname in ombt_confs[agent_type]

- name: Waiting for the controller(s) to finish
  shell: "docker ps | grep controller"
  register: finished
  until: finished.stdout == ""
  delay: 10
  retries: 360
  # NOTE(msimonin): empty grep will exit with a non-zero status
  # just ignoring this case
  ignore_errors: yes
