---
- name: Generate the configuration file
  template:
    src: oslo_messaging.conf.j2
    dest: /oslo_messaging.conf


- name: Start ombt server(s)
  docker_container:
    image: "{{ ombt_version }}"
    command: "{{ item.command }}"
    name: "{{ item.name }}"
    detach: "{{ item.detach }}"
    network_mode: host
    state: started
    volumes:
      - /oslo_messaging.conf:/oslo_messaging.conf
  with_items: "{{ ombt_confs[agent_type][inventory_hostname] }}"
  when: inventory_hostname in ombt_confs[agent_type]
