FROM phusion/baseimage:0.9.22

MAINTAINER "matthieu.simonin@inria.fr"

RUN apt update && apt install -y software-properties-common
RUN add-apt-repository -y ppa:qpid/released
RUN apt update && apt install -y\
  make\
  cmake\
  gcc\
  git\
  python-dev\
  python-qpid-proton\
  python-pip\
  libsasl2-2\
  libsasl2-dev\
  libsasl2-modules\
  libssl-dev


RUN git clone --depth 1 --branch 0.18.0 https://github.com/apache/qpid-proton /opt/qpid-proton
WORKDIR /opt/qpid-proton

RUN mkdir build
WORKDIR build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/usr
RUN make
RUN make install


RUN git clone --depth 1 --branch 1.0.0 https://github.com/apache/qpid-dispatch /opt/qpid-dispatch
WORKDIR /opt/qpid-dispatch

RUN mkdir build
WORKDIR /opt/qpid-dispatch/build
RUN cmake ..
RUN make
RUN make install

CMD ["qdrouterd"]
